import {
  Driver,
  Order,
  DeliveryRoute,
  User,
  Log,
  Location,
  DEFAULT_DRIVER_LAT,
  DEFAULT_DRIVER_LNG,
  OrderStatus,
} from './types';

export const mockDrivers: Driver[] = [
  {
    id: 1,
    name: 'علی احمدی',
    car: 'پراید 131',
    lat: DEFAULT_DRIVER_LAT,
    lng: DEFAULT_DRIVER_LNG,
    capacity: 50,
    priority: 1,
    description: 'راننده با تجربه - منطقه شمال تهران',
    isActive: true,
  },
  {
    id: 2,
    name: 'محمد رضایی',
    car: 'پژو 206',
    lat: DEFAULT_DRIVER_LAT + 0.01,
    lng: DEFAULT_DRIVER_LNG + 0.01,
    capacity: 40,
    priority: 2,
    description: 'راننده منطقه غرب تهران',
    isActive: true,
  },
  {
    id: 3,
    name: 'حسین کریمی',
    car: 'سمند LX',
    lat: DEFAULT_DRIVER_LAT - 0.01,
    lng: DEFAULT_DRIVER_LNG - 0.01,
    capacity: 60,
    priority: 3,
    description: 'راننده منطقه جنوب تهران',
    isActive: true,
  },
  {
    id: 4,
    name: 'رضا محمدی',
    car: 'تیبا',
    lat: DEFAULT_DRIVER_LAT + 0.02,
    lng: DEFAULT_DRIVER_LNG - 0.02,
    capacity: 35,
    priority: 4,
    description: 'راننده منطقه شرق تهران',
    isActive: false,
  },
];

export const mockUsers: User[] = [
  {
    id: 1,
    name: 'مدیر سیستم',
    username: 'admin',
    phone: '09121234567',
    role: 'ADMIN',
    status: 'ACTIVE',
    permissions: ['VIEW_DASHBOARD', 'MANAGE_DRIVERS', 'MANAGE_ORDERS', 'MANAGE_DELIVERY', 'MANAGE_USERS', 'VIEW_REPORTS', 'EDIT_SETTINGS'],
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 2,
    name: 'سارا کریمی',
    username: 'sara.karimi',
    phone: '09129876543',
    role: 'MANAGER',
    status: 'ACTIVE',
    permissions: ['VIEW_DASHBOARD', 'MANAGE_DRIVERS', 'MANAGE_ORDERS', 'MANAGE_DELIVERY', 'VIEW_REPORTS'],
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-02-15'),
  },
  {
    id: 3,
    name: 'امیر حسینی',
    username: 'amir.hosseini',
    phone: '09123456789',
    role: 'OPERATOR',
    status: 'ACTIVE',
    permissions: ['VIEW_DASHBOARD', 'MANAGE_ORDERS', 'MANAGE_DELIVERY'],
    createdAt: new Date('2025-03-10'),
    updatedAt: new Date('2025-03-10'),
  },
  {
    id: 4,
    name: 'زهرا احمدی',
    username: 'zahra.ahmadi',
    phone: '09127654321',
    role: 'DRIVER',
    status: 'INACTIVE',
    permissions: ['VIEW_DASHBOARD'],
    createdAt: new Date('2025-04-05'),
    updatedAt: new Date('2025-04-05'),
  },
];

export const mockOrders: Order[] = [
  {
    id: 1,
    trackingCode: 'FLW-1234567',
    address: 'تهران، خیابان ولیعصر، پلاک 123',
    assignType: 'AI',
    contactPerson: 'آقای محمدی',
    deliveryTime: new Date('2026-05-06T10:00:00'),
    description: 'بسته شکستنی - با احتیاط حمل شود',
    status: OrderStatus.ASSIGNED,
    mobile: '09121234567',
    locationName: 'دفتر مرکزی',
    returnTime: null,
    productCode: 'PRD-001',
    lat: DEFAULT_DRIVER_LAT + 0.005,
    lng: DEFAULT_DRIVER_LNG + 0.005,
    driver: mockDrivers[0],
    driverId: 1,
    pickupPlaceId: 1,
    dropoffPlaceId: 2,
    createdAt: new Date('2026-05-05T08:00:00'),
    updatedAt: new Date('2026-05-05T08:00:00'),
  },
  {
    id: 2,
    trackingCode: 'FLW-2345678',
    address: 'تهران، خیابان شریعتی، کوچه گل، پلاک 45',
    assignType: 'MANUAL',
    contactPerson: 'خانم احمدی',
    deliveryTime: new Date('2026-05-06T14:00:00'),
    description: 'تحویل فوری',
    status: OrderStatus.ASSIGNED,
    mobile: '09129876543',
    locationName: 'منزل',
    returnTime: new Date('2026-05-06T16:00:00'),
    productCode: 'PRD-002',
    lat: DEFAULT_DRIVER_LAT - 0.003,
    lng: DEFAULT_DRIVER_LNG + 0.008,
    driver: mockDrivers[1],
    driverId: 2,
    pickupPlaceId: 1,
    dropoffPlaceId: 2,
    createdAt: new Date('2026-05-05T09:00:00'),
    updatedAt: new Date('2026-05-05T09:00:00'),
  },
  {
    id: 3,
    trackingCode: 'FLW-3456789',
    address: 'تهران، میدان آزادی، خیابان آزادی، پلاک 78',
    assignType: 'AI',
    contactPerson: 'آقای کریمی',
    deliveryTime: new Date('2026-05-06T16:00:00'),
    description: 'بسته سنگین',
    status: OrderStatus.PENDING,
    mobile: null,
    locationName: null,
    returnTime: null,
    productCode: null,
    lat: DEFAULT_DRIVER_LAT + 0.012,
    lng: DEFAULT_DRIVER_LNG - 0.004,
    driver: null,
    driverId: null,
    pickupPlaceId: 2,
    dropoffPlaceId: 1,
    createdAt: new Date('2026-05-05T10:00:00'),
    updatedAt: new Date('2026-05-05T10:00:00'),
  },
  {
    id: 4,
    trackingCode: 'FLW-4567890',
    address: 'تهران، خیابان انقلاب، نبش خیابان حافظ',
    assignType: 'MANUAL',
    contactPerson: 'خانم رضایی',
    deliveryTime: new Date('2026-05-07T09:00:00'),
    description: 'مدارک اداری مهم',
    status: OrderStatus.ASSIGNED,
    mobile: '09123456789',
    locationName: 'اداره',
    returnTime: null,
    productCode: 'PRD-003',
    lat: DEFAULT_DRIVER_LAT - 0.007,
    lng: DEFAULT_DRIVER_LNG + 0.002,
    driver: mockDrivers[2],
    driverId: 3,
    pickupPlaceId: 1,
    dropoffPlaceId: 2,
    createdAt: new Date('2026-05-05T11:00:00'),
    updatedAt: new Date('2026-05-05T11:00:00'),
  },
  {
    id: 5,
    trackingCode: 'FLW-5678901',
    address: 'تهران، سعادت آباد، میدان کاج',
    assignType: 'AI',
    contactPerson: 'آقای صادقی',
    deliveryTime: new Date('2026-05-07T11:00:00'),
    description: 'بسته الکترونیکی',
    status: OrderStatus.ASSIGNED,
    mobile: '09127654321',
    locationName: 'فروشگاه',
    returnTime: null,
    productCode: 'PRD-004',
    lat: DEFAULT_DRIVER_LAT + 0.015,
    lng: DEFAULT_DRIVER_LNG + 0.012,
    driver: mockDrivers[0],
    driverId: 1,
    pickupPlaceId: 2,
    dropoffPlaceId: 1,
    createdAt: new Date('2026-05-05T12:00:00'),
    updatedAt: new Date('2026-05-05T12:00:00'),
  },
];

export const mockDeliveryRoutes: DeliveryRoute[] = [
  {
    id: 1,
    routeName: 'مسیر شمال تهران',
    driver: mockDrivers[0],
    orders: [mockOrders[0], mockOrders[4]],
    totalCapacity: 25,
    deliverySequence: [1, 5],
    timeWindow: {
      start: new Date('2026-05-06T08:00:00'),
      end: new Date('2026-05-06T12:00:00'),
    },
  },
  {
    id: 2,
    routeName: 'مسیر غرب تهران',
    driver: mockDrivers[1],
    orders: [mockOrders[1]],
    totalCapacity: 15,
    deliverySequence: [2],
    timeWindow: {
      start: new Date('2026-05-06T13:00:00'),
      end: new Date('2026-05-06T17:00:00'),
    },
  },
  {
    id: 3,
    routeName: 'مسیر جنوب تهران',
    driver: mockDrivers[2],
    orders: [mockOrders[3]],
    totalCapacity: 10,
    deliverySequence: [4],
    timeWindow: {
      start: new Date('2026-05-07T08:00:00'),
      end: new Date('2026-05-07T11:00:00'),
    },
  },
];

export const mockLogs: Log[] = [
  {
    id: 1,
    user: 'مدیر سیستم',
    action: 'CREATE_ORDER',
    entity: 'order',
    description: 'سفارش جدید با کد FLW-1234567 ایجاد شد',
    createdAt: new Date('2026-05-05T08:15:00'),
  },
  {
    id: 2,
    user: 'سارا کریمی',
    action: 'ASSIGN_DRIVER',
    entity: 'order',
    description: 'راننده علی احمدی به سفارش FLW-1234567 اختصاص داده شد',
    createdAt: new Date('2026-05-05T08:30:00'),
  },
  {
    id: 3,
    user: 'مدیر سیستم',
    action: 'CREATE_DRIVER',
    entity: 'driver',
    description: 'راننده جدید رضا محمدی اضافه شد',
    createdAt: new Date('2026-05-05T09:00:00'),
  },
  {
    id: 4,
    user: 'امیر حسینی',
    action: 'UPDATE_ORDER',
    entity: 'order',
    description: 'سفارش FLW-2345678 به‌روزرسانی شد - وضعیت: در مسیر',
    createdAt: new Date('2026-05-05T10:00:00'),
  },
  {
    id: 5,
    user: 'مدیر سیستم',
    action: 'UPDATE_DRIVER',
    entity: 'driver',
    description: 'اطلاعات راننده محمد رضایی به‌روزرسانی شد',
    createdAt: new Date('2026-05-05T11:00:00'),
  },
  {
    id: 6,
    user: 'سارا کریمی',
    action: 'CREATE_ORDER',
    entity: 'order',
    description: 'سفارش جدید با کد FLW-3456789 ایجاد شد',
    createdAt: new Date('2026-05-05T11:30:00'),
  },
  {
    id: 7,
    user: 'مدیر سیستم',
    action: 'CREATE_USER',
    entity: 'user',
    description: 'کاربر جدید زهرا احمدی ایجاد شد',
    createdAt: new Date('2026-05-05T12:00:00'),
  },
  {
    id: 8,
    user: 'امیر حسینی',
    action: 'DELETE_ORDER',
    entity: 'order',
    description: 'سفارش FLW-9999999 حذف شد',
    createdAt: new Date('2026-05-05T14:00:00'),
  },
  {
    id: 9,
    user: 'مدیر سیستم',
    action: 'UPDATE_USER',
    entity: 'user',
    description: 'نقش کاربر امیر حسینی به OPERATOR تغییر کرد',
    createdAt: new Date('2026-05-06T08:00:00'),
  },
  {
    id: 10,
    user: 'سارا کریمی',
    action: 'ASSIGN_DRIVER',
    entity: 'order',
    description: 'راننده حسین کریمی به سفارش FLW-4567890 اختصاص داده شد',
    createdAt: new Date('2026-05-06T09:30:00'),
  },
];

export const mockLocations: Location[] = [
  {
    id: 1,
    name: 'دفتر مرکزی',
    title: 'دفتر مرکزی',
    address: 'تهران، خیابان ولیعصر، پلاک 123',
    lat: DEFAULT_DRIVER_LAT + 0.005,
    lng: DEFAULT_DRIVER_LNG + 0.005,
    description: 'دفتر مرکزی شرکت - طبقه سوم',
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 2,
    name: 'منزل',
    title: 'منزل',
    address: 'تهران، خیابان شریعتی، کوچه گل، پلاک 45',
    lat: DEFAULT_DRIVER_LAT - 0.003,
    lng: DEFAULT_DRIVER_LNG + 0.008,
    description: null,
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 3,
    name: 'اداره',
    title: 'اداره',
    address: 'تهران، خیابان انقلاب، نبش خیابان حافظ',
    lat: DEFAULT_DRIVER_LAT - 0.007,
    lng: DEFAULT_DRIVER_LNG + 0.002,
    description: 'طبقه دوم - واحد ۲۰۴',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 4,
    name: 'فروشگاه',
    title: 'فروشگاه',
    address: 'تهران، سعادت آباد، میدان کاج',
    lat: DEFAULT_DRIVER_LAT + 0.015,
    lng: DEFAULT_DRIVER_LNG + 0.012,
    description: 'فروشگاه مرکزی - درب شرقی',
    createdAt: new Date('2026-02-15'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 5,
    name: 'انبار شمال',
    title: 'انبار شمال',
    address: 'تهران، شمیرانات، خیابان شریعتی شمالی، کوچه انبار',
    lat: DEFAULT_DRIVER_LAT + 0.025,
    lng: DEFAULT_DRIVER_LNG - 0.01,
    description: 'انبار اصلی کالاها',
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 6,
    title: 'شعبه غرب',
    address: 'تهران، شهرک غرب، بلوار فرحزادی، پلاک ۸۵',
    lat: DEFAULT_DRIVER_LAT + 0.008,
    lng: DEFAULT_DRIVER_LNG - 0.02,
    description: 'شعبه منطقه غرب تهران',
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-15'),
  },
];
